version: "3.4"
services:
    nopcommerce_web:
        build: .
        container_name: nopcommerce
        restart: "always"
        ports:
            - "80:80"
        volumes:
            - nopcommerce_data:/app
volumes:
  nopcommerce_data:            